config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'people#index'
  resources :people
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: {message: "标题不能为空"}
  validates :content, presence: {message: "内容不能为空"}
  validates :user_id, presence: {message: "用户不能为空"}

  belongs_to :user
  has_and_belongs_to_many :tags

  def tags_string= one_tags
    one_tags.split(',').each do |tag|
      one_tag = Tag.find_by(title: tag)
      one_tag = Tag.new(title: tag) unless one_tag
      # 下面的追加操作会自动帮我们保存一个新的tag,如果one_tag不存在的话
      self.tags << one_tag
    end
  end

  def content= one_content
    write_attribute :content, "-----#{one_content}----"
  end
end

app/models/file_manage.rb
class FileManage < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  validates_presence_of :avatar
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :tags, :as => :tagable

  attr_accessor :tag_names
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :tags, :as => :tagable
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :tagable, :polymorphic => true
end

app/models/user.rb
class User < ApplicationRecord

  validates :username, presence: {message: "用户名不能为空"}
  validates :username, uniqueness: {message: "用户名已存在"}
  # validates :password, presence: {message: "密码不能为空"}
  validates :password, length: {minimum: 6,message:"密码长度最短为6位"}

  has_many :blogs
  has_many :public_blogs, -> {where(is_public: true)},class_name: "Blog"
  has_one :latest_blog, ->{order("id desc")},class_name: "Blog"

  attr_accessor :old_password
  attr_accessor :password
  attr_accessor :password_confirmation

  validate :validate_password, on: :create
  before_create :set_password

  def self.authenticate username,password
    user = User.find_by(username: username)
    if user and user.valid_password? password
      user
    else
      nil
    end
  end

  def valid_password? password
    self.crypted_password == Digest::SHA256.hexdigest(password + self.salt)
  end

  private

  def validate_password
    if self.password.blank?
      self.errors.add(:password,"密码不能为空")
      return false
    end
    unless self.password == self.password_confirmation
      self.errors.add(:password_confirmation,"密码不一致")
      return false
    end

    return true
  end

  def set_password
    self.salt = Time.now.to_i
    self.crypted_password = Digest::SHA256.hexdigest(self.password + self.salt)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :auth_user, except: [:index,:show]

  def index
    @blogs = Blog.page(params[:page] || 1).
        per_page(params[:per_page] || 10).
        order('id desc').where(is_public: true).
        includes(:tags,:user)
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = current_user.blogs.new(blog_attrs)
    # @blog = Blog.new(blog_attrs)
    # @blog.user = current_user
    if @blog.save
      flash[:notice] = '创建成功'
      redirect_to blogs_path
    else
      flash[:notice] = '博客创建失败'
      render action: :new
    end
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def edit
    @blog = current_user.blogs.find(params[:id])
    render action: :new
  end

  def update
    @blog = current_user.blogs.find(params[:id])
    if @blog.update_attributes(blog_attrs)
      @blog.tags.destroy_all

      flash[:notice] = '博客更新成功'
      redirect_to blogs_path
    else
      flash[:notice] = '博客更新失败'
      render action: :new
    end
  end

  private

  def blog_attrs
    params.require(:blog).permit(:title,:content,:is_public,:tags_string)
  end
end

app/controllers/file_managements_controller.rb
class FileManagementsController < ApplicationController
  def index
    @image_urls = FileManage.all.collect{ |f|
      {
          src:f.avatar.url,
          title: ''
      }
    }
  end

  def show

  end

  def new
    @file = FileManage.new()
  end

  def create
    @file = FileManage.new()
    @file.avatar = params[:file_manage][:avatar] if params[:file_manage].present?
    @file.save
  end

  private
  def file_manage_params
    params.require(:file_manage).permit(:avatar)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index

  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_attrs)
    if @person.save
      params[:person][:tag_names].split(",").each do |tag|
        one_tag = Tag.find_by(name: tag)
        one_tag = Tag.new(name: tag) unless one_tag
        # 下面的追加操作会自动帮我们保存一个新的tag,如果one_tag不存在的话
        @person.tags << one_tag
      end
      redirect_to person_path(@person)
    else
      render action: :new
    end
  end

  def edit

  end

  def update

  end

  def show
    @person = Person.find(params[:id])
  end

  def destroy

  end

  private
  def person_attrs
    params.require(:person).permit(:username,:tag_names)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    @user = User.authenticate(params[:username],params[:password])
    if @user
      login_user @user
      # flash[:notice] = "登录成功"
      # redirect_to root_path
      render json: {
                 status: 'ok',
                 msg: {
                     redirect_url: root_path
                 }
             }
    else
      # flash[:notice] = "用户名或密码不正确"
      # render action: :new
      render json: {
                 status: 'error',
                 msg: "用户名或密码不正确"
             }
    end
  end

  def destroy
    logout_user

    flash[:notice] = "退出成功"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :auth_user, only: [:index]

  def index
    @users = User.page(params[:page] || 1).
        per_page(params[:per_page] || 10).
        order('id desc')
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_attrs)
    if @user.save
      UserMailer.sign_up(@user).deliver_now
      flash[:notice]="注册成功，请登录"
      redirect_to new_session_path
    else
      render action: :new
    end
  end

  def blogs
    @blogs = current_user.blogs.page(params[:page] || 1).
        per_page(params[:per_page] || 10).
        order('id desc')
  end

  private

  def user_attrs
    params.require(:user).permit(:username,:password,:password_confirmation,:email_address)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/file_managements_helper.rb
module FileManagementsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blogs/_blogs.html.erb
<table class="table">
  <tr>
    <th>ID</th>
    <th>标题</th>
    <th>作者</th>
    <th></th>
  </tr>
  <%@blogs.each do |blog|%>
      <tr>
        <td><%= blog.id%></td>
        <td>
          <%=link_to blog.title,blog_path(blog)%>
          <% blog.tags.each do |tag|%>
            <span class="label label-default"><%= tag.title%></span>
          <% end %>
        </td>
        <td><%= blog.user.username%></td>
        <td>
          <% if blog.user == current_user%>
            <%= blog.is_public ? '公开':'不公开'%>
            <%= link_to "编辑",edit_blog_path(blog)%>
          <% end %>
        </td>
      </tr>
  <%end%>
</table>
<%= will_paginate @blogs%>

app/views/blogs/index.html.erb
<h1>博客</h1>
<div>
  <%= link_to '创建博客',new_blog_path,class: 'btn btn-primary'%>
  <% if logged_in?%>
    <%= link_to '我的博客',blogs_user_path(current_user),class: 'btn btn-default'%>
  <%end%>
</div>
<div class="row">
  <div class="col-sm-12">
    <%= render 'blogs'%>
  </div>
</div>

app/views/blogs/new.html.erb
<h1><%= @blog.new_record? ? '创建':'编辑'%>博客</h1>

<div class="row">
  <div class="col-sm-5">
    <%= form_for @blog ,url: (@blog.new_record? ? blogs_path : blog_path(@blog)) do |f|%>
        <div class="form-group">
          <ul class="list-unstyled">
            <% @blog.errors.messages.values.flatten.each do |error|%>
                <li><i class="fa fa-exclamation-circle"></i><%=error%></li>
            <%end%>
          </ul>
        </div>
        <div class="form-group">
          <%= f.text_field :title,class: "form-control", placeholder: "标题"%>
        </div>
        <div class="form-group">
          <%= f.text_area :content,class: "form-control", placeholder: "内容"%>
        </div>
        <div class="form-group">
          <%= text_field_tag 'blog[tags_string]',@blog.tags.map(&:title).join(','),class: "form-control"%><small>标签以逗号分隔</small>
        </div>

        <div class="form-group">
          <%= f.select :is_public,[['公开',true],['不公开',false]],{},class: "form-control"%>
        </div>

        <%= f.submit "保存", class: 'btn btn-primary'%>
    <%end%>
  </div>
</div>,

app/views/blogs/show.html.erb
<h1><%= @blog.title%></h1>

<div class="row">
  <div class="col-sm-12">
    <p>
      作者：<%= @blog.user.username%>
    </p>
    <p>
      内容：<%= @blog.content %>
    </p>
    <p>
      时间：<%= @blog.created_at %>
    </p>
  </div>
</div>

app/views/people/index.html.erb
<%= link_to 'Create',new_person_path%>

app/views/people/new.html.erb
<%= form_for @person,url: people_path do |f|%>
    <p>Username:<%=f.text_field :username%></p>
    <p>Tags(Split By ",")<%= f.text_field :tag_names%></p>
    <p><%= f.submit "Submit"%></p>
<%end%>

app/views/people/show.html.erb
<%=@person.username%><br/>
<%=@person.tags.map(&:name).join(',')%>